// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/25/2025, 11:06:37 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Volumes/1TSSD/community/calu_equip_score_calculator/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/1TSSD/community/calu_equip_score_calculator/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/1TSSD/community/calu_equip_score_calculator/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/1TSSD/community/calu_equip_score_calculator/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/1TSSD/community/calu_equip_score_calculator/plugins/**/*.{js,ts,mjs}","/Volumes/1TSSD/community/calu_equip_score_calculator/composables/**/*.{js,ts,mjs}","/Volumes/1TSSD/community/calu_equip_score_calculator/utils/**/*.{js,ts,mjs}","/Volumes/1TSSD/community/calu_equip_score_calculator/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/1TSSD/community/calu_equip_score_calculator/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Volumes/1TSSD/community/calu_equip_score_calculator/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Volumes/1TSSD/community/calu_equip_score_calculator/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;